spring.datasource.url=jdbc:postgresql://localhost:5432/atelierdb
spring.datasource.username=atelieruser
spring.datasource.password=password

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/api/auth/oauth2/callback/google

app.jwt-secret=${JWT_SECRET}
app.frontend-url=http://localhost:5173
aws.s3.bucket=${S3_BUCKET}

aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}