spring.datasource.url=jdbc:postgresql://localhost:5432/atelierdb
spring.datasource.username=atelieruser
spring.datasource.password=password

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

app.frontend-url=http://localhost:5173

aws.s3.endpoint=http://localstack:4566
aws.s3.bucket=${S3_BUCKET}
aws.access-key-id=test
aws.secret-access-key=test
aws.region=us-east-1

spring.config.import=application-secrets.properties

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG